### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by alesapin** [DFined/Orbital#2]
По коду:
1) Какие-то куски дебага https://github.com/DFined/Orbital/blob/master/src/DFined/core/Renderer.java#L53-L59.
2) Не понятно почему в отдельном блоке и надо бы всё таки разбить на несколько строк https://github.com/DFined/Orbital/blob/master/src/DFined/core/Renderer.java#L84
3) `SolarSystemState` -- это набор `CelestialBody`, при этом сам `CelestialBody` использует весь стейт солнечной системы, чтобы посчитать влияние других объектов. Это нельзя назвать ошибкой, но такие взаимные связи усложняют код. `collide` изменяет наш стейт и стейт другого тела https://github.com/DFined/Orbital/blob/master/src/DFined/Physics/CelestialBody.java#L191. Довольно запутано получается.
4) https://github.com/DFined/Orbital/blob/master/src/DFined/Physics/Orbit.java#L23 Не нашел зачем нужен.
5) https://github.com/DFined/Orbital/blob/master/src/DFined/Physics/Orbit.java#L36 тоже будет не нужен.
6) Ещё жестче чем в п. 3 взаимная связь между `Orbit` и `CelestialBody`. Тут точно можно отдельные параметры передавать в update и развязать классы между собой.
7) Почему-то прямо внутри движка инициализируем графику https://github.com/DFined/Orbital/blob/master/src/DFined/Physics/CelestialBody.java#L61, про `PApplet`'ы должно быть только в ui. Тоже самое тут https://github.com/DFined/Orbital/blob/master/src/DFined/Physics/CelestialBody.java#L48.
8) Плохое имя класса, если он не единственный https://github.com/DFined/Orbital/blob/master/src/DFined/core/Parameters.java#L3. `SimluationParameters`, `GameParameters`...
9) Почему бы это https://github.com/DFined/Orbital/blob/master/src/DFined/Physics/Physics.java#L43 не убрать внутрь `SolarSystemState`. Тогда бы класс `Physics` мог бы забыть о существовании `CelestialBody`.
10) Такие вещи всегда пугают https://github.com/DFined/Orbital/blob/master/src/DFined/Physics/Physics.java#L40. Работаем без ошибок? Откуда тут что-то может вылетать? Зачем вообще исключение, может быть диагностического сообщения в логах достаточно? Хотя бы коммент нужен.
11) Useless comment: https://github.com/DFined/Orbital/blob/master/src/DFined/Util.java#L18.

**Comment by DFined** [comment]
Исправлено в 186b80ba4de4cdf46f321bfcd9af7571951e96df
